---
title: "Milestone 2"
author: "Abby LaBreck"
date: "9/25/2020"
output: html_document
---

1.) The first project I looked at was Luke Kolar's project, Discovering "Discovery." This project explored the questions of why 20 year-old electronic dance music still matters today and also what qualities make a song or album so influential. One of the pros of the project, was first and foremost, the passion for Daft Punk's Discovery album Luke expressed through this project. This interest was evident in the background section of the project's site. Another pro was that the data was gathered from a variety of sources. He noted that some datasets were accessible and others were hostile to data scientists and had to be cleaned before use. The wide range of data sources allowed Luke to investigate numerous variables about Discovery, including danceability and valence, as well as popularity over time. The plots were also well formatted and easy to understand, allowing users to adjust the years that were displayed on the plots. In the Potential Connections section of the site, users could choose which songs on the album they would like to compare. The interactivity of the site was a definite pro. A con of the project was that, ultimately, the data gathered did not actually tell anything specific about a song's influence, instead just giving information on popularity and use over time. Luke does say that there is a subjectivity vs. objectivity debate when discussing art and the data collected cannot objectively show why a particular song is influential. Another con was Luke often referred to the idea of "samples" and uses of the album and as someone who is not very familiar with technical music production terminology, I would have liked a key that defined words that are important to understanding the project in its entirety.

2.) The second project I looked at was Benjamin Villa Wiesner's project, "The Sacred and Profane: Metropolitan Emotions," which explored the question of the extent to which different factors affect mental health and emotional well-being in metropolitan areas across the United States. A pro of this project was that all data came from one source, the 89 Metropolitan Statistical Areas from the year 2016. I also liked out Benjamin made plots to represent data on six critical factors linked to emotional well-being, with additional plots to represent variables within those six factors. The data set was extensive and allowed for the creation of numerous plots. Unfortunately, a con of the project was the readability of certain tables and plots. The Correlations Between Variables model was hard to interpret for a general user without extensive knowledge of plots. Also, the Regression table was also a bit challenging to understand because the variable labels on the table were written using underscores and not just words. I think the labels could have been modified for users to better understand the table's meaning. I did like the feature, however, that enabled users to choose their own 5 variables and create their own regression table. 